export enum DeErrorTitle {
  AUTHENTICATION_ERROR = 'Authentifizierungsproblem',
  INVALID_REQUEST = 'Ungültige Anfrage',
  INVALID_CREDENTIALS = 'Ungültige Anmeldedaten',
  LACK_OF_CREDENTIALS = 'Mangel an Anmeldedaten',
  UNAUTHORIZED_ACCESS = 'Unbefugter Zugriff',
  ACCESS_TOKEN_EXPIRED = 'Zugangs-Token abgelaufen',
  RENEW_TOKEN_EXPIRED = 'Erneuerungs-Token abgelaufen',
  INVALID_SIGNUP_DATA = 'Ungültige Anmeldedaten',
  INVALID_SIGNIN_DATA = 'Ungültige Anmeldedaten',
  INTERNAL_SERVER_ERROR = 'Interner Serverfehler',
  NOT_FOUND = 'Ressource nicht gefunden',
  FORBIDDEN = 'Zugriff verweigert',
  USER_NOT_FOUND = 'Benutzer nicht gefunden',
  USER_ALREADY_EXISTS = 'Benutzer existiert bereits',
  INVALID_INPUT = 'Ungültige Eingabe',
  INVALID_EMAIL = 'Ungültige E-Mail',
  INVALID_PASSWORD = 'Ungültiges Passwort',
  INVALID_TOKEN = 'Ungültiges Token',
  EXPIRED_TOKEN = 'Abgelaufener Token',
  ALREADY_VERIFIED = 'Bereits verifiziert',
  EMAIL_NOT_VERIFIED = 'E-Mail nicht verifiziert',
  DATA_ALREADY_EXISTS = 'Daten existieren bereits',
  MISSING_PARAMETERS = 'Fehlende Parameter',
  // Weitere Fehlerarten hinzufügen, falls erforderlich
  CANNOT_SWITCH_ORDER = 'Bestellung kann nicht geändert werden.',
  PREFERENCES_ALREADY_EXISTS = 'Präferenzen existieren bereits',
  MAGASIN_ALREADY_EXISTS = 'Der Laden existiert bereits',
  PRODUCT_ALREADY_EXISTS = 'Das Produkt existiert bereits',
  WISHLIST_ALREADY_EXIST = 'Wunschliste existiert bereits',
  CART_ALREADY_EXIST = 'Warenkorb existiert bereits',
  CATEGORY_ALREADY_EXISTS = 'Die Kategorie existiert bereits',
  ITEM_ALREADY_IN_WISHLIST = 'Artikel ist bereits in der Wunschliste',
  ITEM_ALREADY_IN_CART = 'Artikel ist bereits im Warenkorb',
  ORDER_MUST_INCLUDE_ONE_ITEM = 'Die Bestellung muss mindestens einen Artikel enthalten',
  EMAIL_ALREADY_SUBSCRIBED = 'E-Mail bereits abonniert',
}

export enum DeErrorMessage {
  AUTHENTICATION_ERROR = 'Authentifizierungsfehler. Bitte geben Sie gültige Anmeldedaten an.',
  INVALID_REQUEST = 'Die Anfrage ist ungültig. Bitte überprüfen Sie die Eingaben und versuchen Sie es erneut.',
  INVALID_CREDENTIALS = 'Ungültige Anmeldedaten angegeben. Bitte versuchen Sie es erneut.',
  LACK_OF_CREDENTIALS = 'Die Anfrage enthält keine Anmeldedaten für die Zielressource.',
  UNAUTHORIZED_ACCESS = 'Sie haben keine Berechtigung, auf diese Ressource zuzugreifen.',
  EXPIRED_TOKEN = 'Das angegebene Token ist abgelaufen. Bitte beantragen Sie ein neues Token, um weiterhin auf die Ressourcen zuzugreifen.',
  INVALID_SIGNUP_DATA = 'Ungültige Anmeldedaten. Bitte geben Sie gültige Informationen zur Anmeldung an.',
  INVALID_SIGNIN_DATA = 'Ungültige Anmeldedaten. Bitte geben Sie gültige Informationen zur Anmeldung an.',
  NOT_FOUND = 'Die angeforderte Ressource konnte nicht auf dem Server gefunden werden.',
  FORBIDDEN = 'Sie haben nicht die erforderlichen Berechtigungen, um auf diese Ressource zuzugreifen.',
  USER_NOT_FOUND = 'Der angeforderte Benutzer konnte im System nicht gefunden werden.',
  USER_ALREADY_EXISTS = 'Ein Benutzer mit dieser E-Mail oder dieser Drittanbieter-ID existiert bereits.',
  INVALID_INPUT = 'Die bereitgestellten Eingaben sind ungültig. Bitte überprüfen Sie die Daten und versuchen Sie es erneut.',
  INVALID_EMAIL = 'Ungültige E-Mail angegeben. Bitte geben Sie eine gültige E-Mail-Adresse an.',
  INVALID_PASSWORD = 'Ungültiges Passwort angegeben. Das Passwort muss mindestens 8 Zeichen lang sein und sowohl Buchstaben als auch Zahlen enthalten.',
  INTERNAL_SERVER_ERROR = 'Ein unerwarteter Fehler ist auf dem Server aufgetreten. Bitte versuchen Sie es später erneut oder wenden Sie sich an den Support, um Hilfe zu erhalten.',
  INVALID_TOKEN = 'Das bereitgestellte Token ist ungültig. Bitte geben Sie ein gültiges Token an.',
  ALREADY_VERIFIED = 'Dieses Konto wurde bereits verifiziert.',
  EMAIL_NOT_VERIFIED = 'Die E-Mail-Adresse ist nicht verifiziert. Bitte überprüfen Sie Ihre E-Mail, bevor Sie fortfahren.',
  DATA_ALREADY_EXISTS = 'Die Daten existieren bereits. Bitte geben Sie andere Daten an.',
  MISSING_PARAMETERS = 'Erforderliche Parameter fehlen in der Anfrage.',
  // Weitere Fehlerarten hinzufügen, falls erforderlich
  PASSWORDS_DO_NOT_MATCH = 'Die Passwörter stimmen nicht überein.',
  CANNOT_SWITCH_ORDER = 'Bestellung kann nicht geändert werden. Kein gültiger Artikel gefunden.',
  PREFERENCES_ALREADY_EXISTS = 'Präferenzen existieren bereits. Bitte wählen Sie andere Präferenzen.',
  MAGASIN_ALREADY_EXISTS = 'Der Laden existiert bereits. Bitte wählen Sie einen anderen Laden.',
  PRODUCT_ALREADY_EXISTS = 'Das Produkt existiert bereits. Bitte wählen Sie ein anderes Produkt.',
  WISHLIST_ALREADY_EXIST = 'Die Wunschliste existiert bereits. Bitte aktualisieren Sie Ihre vorhandene Wunschliste.',
  CART_ALREADY_EXIST = 'Der Warenkorb existiert bereits. Bitte aktualisieren Sie Ihren vorhandenen Warenkorb.',
  CATEGORY_ALREADY_EXISTS = 'Diese Kategorie existiert bereits. Bitte wählen Sie eine andere Kategorie.',
  ITEM_ALREADY_IN_WISHLIST = 'Der Artikel befindet sich bereits in Ihrer Wunschliste. Bitte wählen Sie einen anderen Artikel.',
  ITEM_ALREADY_IN_CART = 'Der Artikel befindet sich bereits in Ihrem Warenkorb. Bitte aktualisieren Sie die Menge oder wählen Sie einen anderen Artikel.',
  ORDER_MUST_INCLUDE_ONE_ITEM = 'Ihre Bestellung muss mindestens einen Artikel enthalten. Bitte fügen Sie einen Artikel hinzu, um fortzufahren.',
  EMAIL_ALREADY_SUBSCRIBED = 'Diese E-Mail ist bereits für den Newsletter abonniert. Bitte geben Sie eine andere E-Mail an.',
}
