export enum EnErrorTitle {
  AUTHENTICATION_ERROR = 'Authentication-related issue',
  INVALID_REQUEST = 'Invalid Request',
  INVALID_CREDENTIALS = 'Invalid Credentials',
  LACK_OF_CREDENTIALS = 'Lack of Credentials',
  UNAUTHORIZED_ACCESS = 'Unauthorized Access',
  ACCESS_TOKEN_EXPIRED = 'Expired Access token',
  RENEW_TOKEN_EXPIRED = 'Expired Renew Token',
  INVALID_SIGNUP_DATA = 'Invalid Sign-up Data',
  INVALID_SIGNIN_DATA = 'Invalid Sign-in Data',
  INTERNAL_SERVER_ERROR = 'Internal Server Error',
  NOT_FOUND = 'Resource Not Found',
  FORBIDDEN = 'Access Forbidden',
  USER_NOT_FOUND = 'User Not Found',
  USER_ALREADY_EXISTS = 'User Already Exists',
  INVALID_INPUT = 'Invalid Input',
  INVALID_EMAIL = 'Invalid Email',
  INVALID_PASSWORD = 'Invalid Password',
  INVALID_TOKEN = 'Invalid Token',
  EXPIRED_TOKEN = 'Expired Token',
  ALREADY_VERIFIED = 'Already Verified',
  EMAIL_NOT_VERIFIED = 'Email Not Verified',
  DATA_ALREADY_EXISTS = 'Data Already Exists',
  MISSING_PARAMETERS = 'Missing Parameters',
  // Add more error types as needed
  CANNOT_SWITCH_ORDER = 'Cannot switch order.',
  PREFERENCES_ALREADY_EXISTS = 'Preferences Already Exist',
  MAGASIN_ALREADY_EXISTS = 'Store Already Exists',
  PRODUCT_ALREADY_EXISTS = 'Product Already Exists',
  WISHLIST_ALREADY_EXIST = 'Wishlist Already Exists',
  CART_ALREADY_EXIST = 'Cart Already Exists',
  CATEGORY_ALREADY_EXISTS = 'Category Already Exists',
  ITEM_ALREADY_IN_WISHLIST = 'Item Already in Wishlist',
  ITEM_ALREADY_IN_CART = 'Item Already in Cart',
  ORDER_MUST_INCLUDE_ONE_ITEM = 'Order must include at least one item',
  EMAIL_ALREADY_SUBSCRIBED = 'Email Already Subscribed',
}

export enum EnErrorMessage {
  AUTHENTICATION_ERROR = 'Authentication error. Please provide valid credentials.',
  INVALID_REQUEST = 'The request made is invalid. Please check the input and try again.',
  INVALID_CREDENTIALS = 'Invalid credentials provided. Please try again.',
  LACK_OF_CREDENTIALS = 'The request lacks authentication credentials for the target resource.',
  UNAUTHORIZED_ACCESS = 'You do not have permission to access this resource.',
  EXPIRED_TOKEN = 'The token provided has expired. Please obtain a new token to continue accessing the resources.',
  INVALID_SIGNUP_DATA = 'Invalid sign-up data. Please provide valid information for sign-up.',
  INVALID_SIGNIN_DATA = 'Invalid sign-in data. Please provide valid information for sign-in.',
  NOT_FOUND = 'The requested resource could not be found on the server.',
  FORBIDDEN = 'You do not have the necessary permissions to access this resource.',
  USER_NOT_FOUND = 'The requested user could not be found in the system.',
  USER_ALREADY_EXISTS = 'User with this email or third-party ID already exists.',
  INVALID_INPUT = 'The input provided is invalid. Please check the data and try again.',
  INVALID_EMAIL = 'Invalid email provided. Please provide a valid email address.',
  INVALID_PASSWORD = 'Invalid password provided. Password must be at least 8 characters long and contain both letters and numbers.',
  INTERNAL_SERVER_ERROR = 'An unexpected error occurred on the server. Please try again later or contact support for assistance.',
  INVALID_TOKEN = 'The token provided is invalid. Please provide a valid token.',
  ALREADY_VERIFIED = 'This account has already been verified.',
  EMAIL_NOT_VERIFIED = 'The email address is not verified. Please verify your email before proceeding.',
  DATA_ALREADY_EXISTS = 'The data already exists. Please provide different data.',
  MISSING_PARAMETERS = 'Required parameters are missing from the request.',
  // Add more error types as needed
  PASSWORDS_DO_NOT_MATCH = 'Passwords do not match.',
  CANNOT_SWITCH_ORDER = 'Cannot switch order. No valid item found.',
  PREFERENCES_ALREADY_EXISTS = 'Preferences already exist. Please choose different preferences.',
  MAGASIN_ALREADY_EXISTS = 'Store already exists. Please choose a different store.',
  PRODUCT_ALREADY_EXISTS = 'Product already exists. Please choose a different product.',
  WISHLIST_ALREADY_EXIST = 'The wishlist already exists. Please update your existing wishlist.',
  CART_ALREADY_EXIST = 'The cart already exists. Please update your existing cart.',
  CATEGORY_ALREADY_EXISTS = 'This category already exists. Please choose a different category.',
  ITEM_ALREADY_IN_WISHLIST = 'The item is already in your wishlist. Please choose another item.',
  ITEM_ALREADY_IN_CART = 'The item is already in your cart. Please update the quantity or choose another item.',
  ORDER_MUST_INCLUDE_ONE_ITEM = 'Your order must include at least one item. Please add an item to proceed.',
  EMAIL_ALREADY_SUBSCRIBED = 'This email is already subscribed to the newsletter. Please provide a different email.',
}
