export enum FrErrorTitle {
  AUTHENTICATION_ERROR = "Problème lié à l'authentification",
  INVALID_REQUEST = 'Requête invalide',
  INVALID_CREDENTIALS = 'Identifiants invalides',
  LACK_OF_CREDENTIALS = 'Absence de credentials',
  UNAUTHORIZED_ACCESS = 'Accès non autorisé',
  ACCESS_TOKEN_EXPIRED = "Token d'accès expiré",
  RENEW_TOKEN_EXPIRED = 'Token de renouvellement expiré',
  INVALID_SIGNUP_DATA = "Données d'inscription invalides",
  INVALID_SIGNIN_DATA = 'Données de connexion invalides',
  INTERNAL_SERVER_ERROR = 'Erreur interne du serveur',
  NOT_FOUND = 'Ressource non trouvée',
  FORBIDDEN = 'Accès interdit',
  USER_NOT_FOUND = 'Utilisateur introuvable',
  USER_ALREADY_EXISTS = "L'utilisateur existe déjà",
  INVALID_INPUT = 'Entrée invalide',
  INVALID_EMAIL = 'Email invalide',
  INVALID_PASSWORD = 'Mot de passe invalide',
  INVALID_TOKEN = 'Token invalide',
  EXPIRED_TOKEN = 'Token Expiré',
  ALREADY_VERIFIED = 'Déjà vérifié',
  EMAIL_NOT_VERIFIED = 'Email non vérifié',
  DATA_ALREADY_EXISTS = 'Les données existent déjà',
  MISSING_PARAMETERS = 'Paramètres Manquants',
  // Ajouter d'autres types d'erreur si nécessaire
  CANNOT_SWITCH_ORDER = "Impossible de changer l'ordre.",
  PREFERENCES_ALREADY_EXISTS = 'Les préférences existent déjà',
  MAGASIN_ALREADY_EXISTS = 'Le magasin existe déjà',
  PRODUCT_ALREADY_EXISTS = 'Le produit existe déjà',
  WISHLIST_ALREADY_EXIST = 'La liste de souhaits existe déjà',
  CART_ALREADY_EXIST = 'Le panier existe déjà',
  CATEGORY_ALREADY_EXISTS = 'La catégorie existe déjà',
  ITEM_ALREADY_IN_WISHLIST = "L'article est déjà dans la liste de souhaits",
  ITEM_ALREADY_IN_CART = "L'article est déjà dans le panier",
  ORDER_MUST_INCLUDE_ONE_ITEM = 'La commande doit inclure au moins un article',
  EMAIL_ALREADY_SUBSCRIBED = 'Email déjà abonné',
}

export enum FrErrorMessage {
  AUTHENTICATION_ERROR = "Erreur d'authentification. Veuillez fournir des identifiants valides.",
  INVALID_REQUEST = 'La requête est invalide. Veuillez vérifier les informations et réessayer.',
  INVALID_CREDENTIALS = 'Identifiants invalides fournis. Veuillez réessayer.',
  LACK_OF_CREDENTIALS = "La demande manque de credentials d'authentification pour la ressource cible.",
  UNAUTHORIZED_ACCESS = "Vous n'avez pas la permission d'accéder à cette ressource.",
  EXPIRED_TOKEN = 'Le token fourni a expiré. Veuillez obtenir un nouveau token pour continuer à accéder aux ressources.',
  INVALID_SIGNUP_DATA = "Données d'inscription invalides. Veuillez fournir des informations valides pour l'inscription.",
  INVALID_SIGNIN_DATA = 'Données de connexion invalides. Veuillez fournir des informations valides pour la connexion.',
  NOT_FOUND = "La ressource demandée n'a pas pu être trouvée sur le serveur.",
  FORBIDDEN = "Vous n'avez pas les autorisations nécessaires pour accéder à cette ressource.",
  USER_NOT_FOUND = "L'utilisateur demandé est introuvable dans le système.",
  USER_ALREADY_EXISTS = 'Un utilisateur avec cet email ou cet identifiant tiers existe déjà.',
  INVALID_INPUT = 'Les données fournies sont invalides. Veuillez vérifier les données et réessayer.',
  INVALID_EMAIL = 'Email invalide fourni. Veuillez fournir une adresse email valide.',
  INVALID_PASSWORD = 'Mot de passe invalide fourni. Le mot de passe doit comporter au moins 8 caractères et contenir à la fois des lettres et des chiffres.',
  INTERNAL_SERVER_ERROR = "Une erreur inattendue s'est produite sur le serveur. Veuillez réessayer plus tard ou contacter le support pour obtenir de l'aide.",
  INVALID_TOKEN = 'Le jeton fourni est invalide. Veuillez fournir un token valide.',
  ALREADY_VERIFIED = 'Ce compte a déjà été vérifié.',
  EMAIL_NOT_VERIFIED = "L'adresse email n'est pas vérifiée. Veuillez vérifier votre email avant de continuer.",
  DATA_ALREADY_EXISTS = 'Les données existent déjà. Veuillez fournir des données différentes.',
  MISSING_PARAMETERS = 'Des paramètres requis sont manquants dans la requête.',
  // Ajouter d'autres types d'erreur si nécessaire
  PASSWORDS_DO_NOT_MATCH = 'Les mots de passe ne correspondent pas.',
  CANNOT_SWITCH_ORDER = "Impossible de changer l'ordre. Aucun élément valide trouvé.",
  PREFERENCES_ALREADY_EXISTS = "Les préférences existent déjà. Veuillez choisir d'autres préférences.",
  MAGASIN_ALREADY_EXISTS = 'Le magasin existe déjà. Veuillez choisir un autre magasin.',
  PRODUCT_ALREADY_EXISTS = 'Le produit existe déjà. Veuillez choisir un autre produit.',
  WISHLIST_ALREADY_EXIST = 'La liste de souhaits existe déjà. Veuillez mettre à jour votre liste de souhaits existante.',
  CART_ALREADY_EXIST = 'Le panier existe déjà. Veuillez mettre à jour votre panier existant.',
  CATEGORY_ALREADY_EXISTS = 'Cette catégorie existe déjà. Veuillez choisir une catégorie différente.',
  ITEM_ALREADY_IN_WISHLIST = "L'article est déjà dans votre liste de souhaits. Veuillez choisir un autre article.",
  ITEM_ALREADY_IN_CART = "L'article est déjà dans votre panier. Veuillez mettre à jour la quantité ou choisir un autre article.",
  ORDER_MUST_INCLUDE_ONE_ITEM = 'Votre commande doit inclure au moins un article. Veuillez ajouter un article pour continuer.',
  EMAIL_ALREADY_SUBSCRIBED = 'Cet email est déjà abonné à la newsletter. Veuillez fournir un autre email.',
}
