export enum ArErrorTitle {
  AUTHENTICATION_ERROR = "مشكلة متعلقة بالتحقق من الهوية",
  INVALID_REQUEST = "طلب غير صالح",
  INVALID_CREDENTIALS = "بيانات اعتماد غير صحيحة",
  LACK_OF_CREDENTIALS = "نقص في بيانات الاعتماد",
  UNAUTHORIZED_ACCESS = "وصول غير مصرح به",
  ACCESS_TOKEN_EXPIRED = "انتهت صلاحية رمز الوصول",
  RENEW_TOKEN_EXPIRED = "انتهت صلاحية رمز التجديد",
  INVALID_SIGNUP_DATA = "بيانات تسجيل غير صالحة",
  INVALID_SIGNIN_DATA = "بيانات تسجيل دخول غير صالحة",
  INTERNAL_SERVER_ERROR = "خطأ داخلي في الخادم",
  NOT_FOUND = "المورد غير موجود",
  FORBIDDEN = "الوصول ممنوع",
  USER_NOT_FOUND = "المستخدم غير موجود",
  USER_ALREADY_EXISTS = "المستخدم موجود بالفعل",
  INVALID_INPUT = "مدخلات غير صالحة",
  INVALID_CIN = "رقم التعريف الوطني غير صالح",
  INVALID_EMAIL = "بريد إلكتروني غير صالح",
  INVALID_PASSWORD = "كلمة مرور غير صالحة",
  EXPIRED_TOKEN = "الرمز مـنتهي الصلاحية",
  INVALID_TOKEN = "رمز غير صالح",
  ALREADY_VERIFIED = "تم التحقق مسبقًا",
  EMAIL_NOT_VERIFIED = "البريد الإلكتروني غير مُؤكد",
  DATA_ALREADY_EXISTS = "البيانات موجودة بالفعل",
  MISSING_PARAMETERS = "المعطيات المفقودة",
  MISSING_ADMIN_ACCESS_CODE = "رمز الوصول الإداري مفقود",
  INVALID_ADMIN_ACCESS_CODE = "رمز الوصول الإداري غير صالح",

  // Visitor-related
  VISITOR_ALREADY_EXISTS = "الزائر موجود مسبقًا",
  VISITOR_DELETED = "تم حذف الزائر بنجاح",
  VISITOR_DELETED_PREVIOUSLY = "تم حذف هذا الزائر مسبقًا",
  VISITOR_NAME_MISMATCH = "معلومات اسم الزائر غير متطابقة",

  // Visit-related
  VISIT_NOT_FOUND = "الزيارة غير موجودة",
  INVALID_VISIT_DATA = "بيانات زيارة غير صحيحة",
}

export enum ArErrorMessage {
  AUTHENTICATION_ERROR = "خطأ في التحقق من الهوية. يرجى تقديم بيانات اعتماد صحيحة.",
  INVALID_REQUEST = "الطلب غير صالح. يرجى التحقق من البيانات والمحاولة مرة أخرى.",
  INVALID_CREDENTIALS = "تم تقديم بيانات اعتماد غير صحيحة. يرجى المحاولة مرة أخرى.",
  LACK_OF_CREDENTIALS = "الطلب يفتقر إلى بيانات الاعتماد اللازمة للوصول إلى المورد المستهدف.",
  UNAUTHORIZED_ACCESS = "ليس لديك إذن للوصول إلى هذا المورد.",
  EXPIRED_TOKEN = "انتهت صلاحية الرمز المقدم. يرجى الحصول على رمز جديد للاستمرار في الوصول إلى الموارد.",
  INVALID_SIGNUP_DATA = "بيانات تسجيل غير صالحة. يرجى تقديم معلومات صحيحة للتسجيل.",
  INVALID_SIGNIN_DATA = "بيانات تسجيل دخول غير صالحة. يرجى تقديم معلومات صحيحة لتسجيل الدخول.",
  NOT_FOUND = "لم يتم العثور على المورد المطلوب على الخادم.",
  FORBIDDEN = "ليس لديك الأذونات اللازمة للوصول إلى هذا المورد.",
  USER_NOT_FOUND = "المستخدم المطلوب غير موجود في النظام.",
  USER_ALREADY_EXISTS = "يوجد مستخدم بهذا البريد الإلكتروني أو معرف الطرف الثالث بالفعل.",
  INVALID_INPUT = "المدخلات المقدمة غير صالحة. يرجى التحقق من البيانات والمحاولة مرة أخرى.",
  INVALID_CIN = "تم تقديم رقم تعريف وطني غير صالح. يرجى تقديم رقم صحيح.",
  INVALID_EMAIL = "تم تقديم بريد إلكتروني غير صالح. يرجى تقديم عنوان بريد إلكتروني صحيح.",
  INVALID_PASSWORD = "تم تقديم كلمة مرور غير صالحة. يجب أن تتكون كلمة المرور من 8 أحرف على الأقل وتحتوي على أحرف وأرقام.",
  INTERNAL_SERVER_ERROR = "حدث خطأ غير متوقع على الخادم. يرجى المحاولة مرة أخرى لاحقًا أو الاتصال بالدعم للحصول على المساعدة.",
  INVALID_TOKEN = "الرمز المقدم غير صالح. يرجى تقديم رمز صالح.",
  ALREADY_VERIFIED = "تم التحقق من هذا الحساب مسبقًا.",
  EMAIL_NOT_VERIFIED = "عنوان البريد الإلكتروني غير مُؤكد. يُرجى تأكيد بريدك الإلكتروني قبل المتابعة.",
  DATA_ALREADY_EXISTS = "البيانات موجودة بالفعل. يرجى تقديم بيانات مختلفة.",
  MISSING_PARAMETERS = "المعطيات المطلوبة مفقودة في الطلب.",
  MISSING_ADMIN_ACCESS_CODE = "رمز الوصول الإداري مطلوب للتسجيل.",
  INVALID_ADMIN_ACCESS_CODE = "رمز الوصول الإداري المقدم غير صالح.",

  // Visitor-related
  VISITOR_ALREADY_EXISTS = "الزائر بمعلومات المقدمة موجود مسبقًا في النظام.",
  VISITOR_DELETED = "تم حذف الزائر من النظام بنجاح.",
  VISITOR_DELETED_PREVIOUSLY = "تم حذف هذا الزائر مسبقًا. يرجى التواصل مع الدعم لمزيد من المساعدة.",
  VISITOR_NAME_MISMATCH = "معلومات الاسم المقدمة للزائر لا تطابق السجل الحالي. يرجى التحقق من البيانات.",

  // Visit-related
  VISIT_NOT_FOUND = "لم يتم العثور على الزيارة المطلوبة. يرجى التحقق من معرف الزيارة.",
  INVALID_VISIT_DATA = "تم تقديم بيانات زيارة غير صحيحة. يرجى مراجعة المدخلات والمحاولة مرة أخرى.",
}
